#!/bin/sh

export EDITOR=vim
export LC_COLLATE=C
export OWLMAN_ASK_EDIT=false
export PAGER=less
export PATH="/opt/chefdk/bin:$HOME/local/bin:$HOME/bin:$HOME/.rbenv/bin:$HOME/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/android-sdk/platform-tools:/usr/bin/core_perl:/usr/bin/vendor_perl:/usr/local/ittools/arcanist/bin:/usr/texbin:/opt/local/bin"
export VISUAL=vim
export PYTHONDONTWRITEBYTECODE=1

case $(uname -s) in
    Darwin) export MAILCAPS="$HOME/.config/mailcap/mac" ;;
    Linux) export MAILCAPS="$HOME/.config/mailcap/linux" ;;
esac
