#!/bin/sh

export EDITOR=vim
export LC_COLLATE=C
export PAGER=less
export VISUAL=vim
export PYTHONDONTWRITEBYTECODE=1
export PYTHONSTARTUP="$HOME/.pythonrc"
export BROWSER=chromium
export NSS_DEFAULT_DB_TYPE=sql

# Allow $config home, which comes from shell init
# shellcheck disable=SC2154
{
    export PATH="/usr/share/bcc/tools:/opt/chefdk/bin:$config_home/local/bin:$config_home/bin:$config_home/.rbenv/bin:$config_home/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/android-sdk/platform-tools:/usr/bin/core_perl:/usr/bin/vendor_perl:/usr/local/ittools/arcanist/bin:/usr/texbin:/opt/local/bin:$HOME/.pyenv/bin"
    export MAILCAPS=$config_home/.config/mailcap/linux
}

umask 0022
