#!/bin/bash

# All in one big subshell to avoid pollution

if [[ $TERM == linux ]]; then
  reset
  (
    color00="00/2b/36" # Base 00 - Black
    color01="dc/32/2f" # Base 08 - Red
    color02="85/99/00" # Base 0B - Green
    color03="b5/89/00" # Base 0A - Yellow
    color04="26/8b/d2" # Base 0D - Blue
    color05="6c/71/c4" # Base 0E - Magenta
    color06="2a/a1/98" # Base 0C - Cyan
    color07="93/a1/a1" # Base 05 - White
    color08="65/7b/83" # Base 03 - Bright Black
    color09=$color01 # Base 08 - Bright Red
    color10=$color02 # Base 0B - Bright Green
    color11=$color03 # Base 0A - Bright Yellow
    color12=$color04 # Base 0D - Bright Blue
    color13=$color05 # Base 0E - Bright Magenta
    color14=$color06 # Base 0C - Bright Cyan
    color15="fd/f6/e3" # Base 07 - Bright White
    color16="cb/4b/16" # Base 09
    color17="d3/36/82" # Base 0F
    color18="07/36/42" # Base 01
    color19="58/6e/75" # Base 02
    color20="83/94/96" # Base 04
    color21="ee/e8/d5" # Base 06

    if [ -n "$TMUX" ]; then
      # Tell tmux to pass the escape sequences through
      # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
      put_template() { printf '\033Ptmux;\033\033]4;%d;rgb:%s\033\033\\\033\\' $@; }
      put_template_var() { printf '\033Ptmux;\033\033]%d;rgb:%s\033\033\\\033\\' $@; }
      put_template_custom() { printf '\033Ptmux;\033\033]%s%s\033\033\\\033\\' $@; }
    elif [ "${TERM%%[-.]*}" = "screen" ]; then
      # GNU screen (screen, screen-256color, screen-256color-bce)
      put_template() { printf '\033P\033]4;%d;rgb:%s\007\033\\' $@; }
      put_template_var() { printf '\033P\033]%d;rgb:%s\007\033\\' $@; }
      put_template_custom() { printf '\033P\033]%s%s\007\033\\' $@; }
    elif [ "${TERM%%-*}" = "linux" ]; then
      put_template() { [ $1 -lt 16 ] && printf "\e]P%x%s" $1 $(echo $2 | sed 's/\///g'); }
      put_template_var() { true; }
      put_template_custom() { true; }
    else
      put_template() { printf '\033]4;%d;rgb:%s\033\\' $@; }
      put_template_var() { printf '\033]%d;rgb:%s\033\\' $@; }
      put_template_custom() { printf '\033]%s%s\033\\' $@; }
    fi

    # 16 color space
    put_template 0  $color00
    put_template 1  $color01
    put_template 2  $color02
    put_template 3  $color03
    put_template 4  $color04
    put_template 5  $color05
    put_template 6  $color06
    put_template 7  $color07
    put_template 8  $color08
    put_template 9  $color09
    put_template 10 $color10
    put_template 11 $color11
    put_template 12 $color12
    put_template 13 $color13
    put_template 14 $color14
    put_template 15 $color15

    # 256 color space
    put_template 16 $color16
    put_template 17 $color17
    put_template 18 $color18
    put_template 19 $color19
    put_template 20 $color20
    put_template 21 $color21
  )
fi
