#!/usr/bin/env bash

[[ $BASH_VERSION == 4.* ]] || exec /usr/local/bin/bash "$0" "$@"

if [[ $1 != '--no-os-check' ]]; then
    case $(uname -s) in
        Darwin) git checkout mac ;;
        Linux) git checkout linux ;;
        *)
            printf 'Unknown kernel "%s".' 1>&2
            exit 1
        ;;
    esac
fi

shopt -s dotglob extglob globstar nullglob

git clean -dffx
git submodule update --init --recursive

if [[ $0 == /* ]]; then
    location=${0%/*}
else
    location=$PWD/${0#./}
    location=${location%/*}
fi

decrypt_pgp=0
if command -v gpg >/dev/null >/dev/null 2>&1 && gpg --list-secret-keys | grep -q 0xDF8D21B616118070; then
    decrypt_pgp=1
fi

for file in "$location"/**/*; do
    bare="${file#$location/}"

    case "$bare" in
        .git|.git/*|.gitignore|.gitmodules|setup|*/.gitkeep|README.md) continue ;;
    esac

    if [[ $file == *.gpg ]]; then
        (( decrypt_pgp )) || continue

        output_file=${file%.gpg}

        gpg --output "$output_file" -d "$file"

        case $output_file in
            */bin/*) gpg_mode=0700 ;;
            *) gpg_mode=0600 ;;
        esac

        chmod "$gpg_mode" "$output_file"

        # Use the decrypted file going forwards
        file=$output_file
        bare="${file#$location/}"
    fi

    if [[ -d "$file" ]]; then
        if [[ -L ~/"$bare" ]]; then
            rm ~/"$bare"
        fi
        mkdir -m700 -p ~/"$bare"
    else
        ln -sfn "$file" ~/"$bare"
    fi
done

deleted=()
if [[ -f ~/.dfsha ]]; then
    mapfile -t deleted < <(git diff --name-status "$(<~/.dfsha)" HEAD | sed -n 's/^D[[:blank:]]//p' | sed 's/\.gpg$//')
fi

if (( "${#deleted[@]}" )); then
    printf 'Files removed since last setup:\n'
    printf '  ~/%q\n' "${deleted[@]}"
    printf '\nRemove files from home directory? '
    read -r delete_reply
    if [[ $delete_reply == [yY] ]]; then
        ( cd && rm -r "${deleted[@]}" )
    fi
fi

git rev-parse HEAD > ~/.dfsha
