#!/usr/bin/env bash

[[ $BASH_VERSION == 4.* ]] || exec /usr/local/bin/bash "$0" "$@"

shopt -s dotglob extglob globstar nullglob

git clean -dffx
git submodule update --init --recursive

# Using `submodule update` is weird with -c http.proxy=..., see
# http://thread.gmane.org/gmane.comp.version-control.git/261223

git submodule init

if [[ $0 == /* ]]; then
    location=${0%/*}
else
    location=$PWD/${0#./}
    location=${location%/*}
fi

# TODO: we need to not make these manual
rm -rf ~/.vim/bundle ~/.sshrc.d

decrypt_pgp=0
if command -v gpg >/dev/null >/dev/null 2>&1 && gpg --list-secret-keys | grep -q 0xDF8D21B616118070; then
    decrypt_pgp=1
fi

for file in "$location"/**/*; do
    bare="${file#$location/}"

    case "$bare" in
        .git|.git/*|.gitignore|.gitmodules|setup|*/.gitkeep|README.md) continue ;;
    esac

    if [[ $file == *.gpg ]]; then
        (( decrypt_pgp )) || continue

        output_file=${file%.gpg}

        gpg --batch --yes --output "$output_file" -d "$file"

        case $output_file in
            */bin/*) gpg_mode=0700 ;;
            *) gpg_mode=0600 ;;
        esac

        [[ -x "$file" ]] && gpg_mode=0700

        chmod "$gpg_mode" "$output_file"

        # Use the decrypted file going forwards
        file=$output_file
        bare="${file#$location/}"
    fi

    if [[ -d "$file" ]] && ! [[ -L "$file" ]]; then
        if [[ -L ~/"$bare" ]]; then
            rm ~/"$bare"
        fi
        mkdir -m755 -p ~/"$bare"
    else
        link=$HOME/$bare
        real_link=$(readlink -f "$link")
        real_file=$(readlink -f "$file")
        # If we already linked this file due to a directory symlink inside the
        # dotfiles, don't try and link it again (see issue #1)
        [[ $real_link != "$real_file" ]] && ln -sfn "$file" ~/"$bare"
    fi
done

deleted=()
if [[ -f ~/.dfsha ]]; then
    mapfile -t deleted < <(git diff --name-status "$(<~/.dfsha)" HEAD | grep -v .vim/bundle | sed -n 's/^D[[:blank:]]//p' | sed 's/\.gpg$//')
fi

if (( "${#deleted[@]}" )); then
    printf 'Files removed since last setup:\n'
    printf '  ~/%q\n' "${deleted[@]}"
    printf '\nRemove files from home directory? '
    read -r delete_reply
    if [[ $delete_reply == [yY] ]]; then
        ( cd && rm -r "${deleted[@]}" )
    fi
fi

git rev-parse HEAD > ~/.dfsha
