#!/bin/bash

alias j=jump
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias v='ls -laFh'
alias sprunge='curl -F "sprunge=<-" http://sprunge.us'
alias sc=systemctl
alias sudo='sudo '
alias proxy='ssh -C2qTnN -D 1337'

alias work-rev-create='autossh -M 22200 -f -N -R 2220:localhost:222 guthrie'
alias home-rev-create='autossh -M 22210 -f -N -R 2221:localhost:222 guthrie'
