#!/bin/bash

alias j=jump
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias v='ls -laFh'
alias sprunge='curl -F "sprunge=<-" http://sprunge.us'
alias sc=systemctl
alias sudo='sudo '
alias proxy='ssh -C2qTnN -D 1337'

alias work-rev-create='autossh -M 12340 -f -N -R 1234:localhost:222 guthrie'
alias home-rev-create='autossh -M 23450 -f -N -R 2345:localhost:222 guthrie'
alias work-rev-connect='ssh -p 1234 localhost'
alias home-rev-connect='ssh -p 2345 localhost'
