#!/bin/bash

HISTCONTROL=ignoredups
HISTFILESIZE=9999999
HISTSIZE=$HISTFILESIZE
PROMPT_COMMAND='history -a'

shopt -s histappend
shopt -s extglob
shopt -s globstar

set +H

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias v='ls -laFh'
alias sprunge='curl -F "sprunge=<-" http://sprunge.us'
alias sc=systemctl
alias ssh='TERM=rxvt ssh'
alias sudo='sudo '
alias proxy='ssh -C2qTnN -D 1337'
alias d=popd

c() {
    if (( $# )); then
        pushd "$@" >/dev/null
    else
        pushd ~ > /dev/null
    fi
}

gitPrompt() {
    git branch --no-color 2>/dev/null | awk '/^\*/ { print ":" $2 }'
}

PS1='\u@\h:\W$(gitPrompt)\$ '
