#!/bin/bash

HISTFILESIZE=
HISTSIZE=

HISTCONTROL=ignoredups
PROMPT_COMMAND='history -a'

shopt -s histappend
shopt -s extglob
shopt -s globstar

set +H

freenode() {
    ssh -L 16000:irc.freenode.net:7000 guthrie -N &
    if [[ "$1" != --init-only ]]; then
        sleep 6
        irssi -c freenode-local
        kill "$!"
    fi
}

quakenet() {
    ssh -L 16001:irc.quakenet.org:6667 guthrie -N &
    if [[ "$1" != --init-only ]]; then
        sleep 6
        irssi -c quakenet-local
        kill "$!"
    fi
}

alias be='bundle exec'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias v='ls -laFh'
alias sprunge='curl -F "sprunge=<-" http://sprunge.us'
alias sc=systemctl
alias ssh='TERM=rxvt ssh'
alias sudo='sudo '
alias proxy='ssh -C2qTnN -D 1337'
alias fp='readlink -f'

gitPrompt() {
    git branch --no-color 2>/dev/null | awk '/^\*/ { print ":" $2 }'
}

PS1='\u@\h:\W$(gitPrompt)\$ '
