#!/bin/bash

awk 'NR==FNR && !/^#/{lines[$0]=FNR;next} lines[$0]==FNR' "$HISTFILE" "$HISTFILE" > "$HISTFILE.compressed" && mv "$HISTFILE.compressed" "$HISTFILE"

HISTCONTROL=ignoredups
HISTFILESIZE=
HISTSIZE=
PROMPT_COMMAND="history -a"

shopt -s histappend
