#!/bin/bash

vpn() {
    case "$2" in
        rmg)
            case "$1" in
                start)
                    sudo pppd call rmg
                    sleep 5
                    sudo ip route add 192.168.12.0/22 via 192.168.12.229 dev ppp0 onlink
                    (
                        cd ~/git/rmg/setupscripts/config
                        perl -e 'use config_ip_addresses;
                                 my $ips = get_ip_address_mappings();
                                 foreach my $ip (values %$ips) {
                                     print "ip route add " . $ip . "/32 via 192.168.12.229 dev ppp0 onlink\n";
                                 }' | sudo sh
                    )
                ;;
                stop)
                    sudo kill "$(head -1 /var/run/ppp-rmg-vpn.pid)"
                ;;
            esac
        ;;
    esac
}
