#!/bin/bash

vpn() {
    case "$2" in
        rmg)
            case "$1" in
                start)
                    sudo pppd call rmg
                    sleep 5
                    sudo ip route add default via 192.168.12.229
                ;;
                stop)
                    sudo kill "$(head -1 /var/run/ppp-rmg-vpn.pid)"
                ;;
            esac
        ;;
    esac
}
