#!/bin/bash

ssh-tic() {
    infocmp | ssh "$@" 't="$(mktemp)" && cat >"$t" && tic "$t"; rm "$t"'
}

ssh-bootstrap() {
    for file in ~/.ssh/*.pub; do
        ssh-copy-id -i "$file" "$@"
    done
    ssh-tic "$@"
}
