#!/bin/bash

vpn() {
    case "$2" in
        rmg)
            case "$1" in
                start)
                    sudo pppd call rmg
                    (
                        sleep 5
                        sudo ip route add 192.168.12.0/22 via 192.168.12.229 dev ppp0 onlink
                    ) &
                ;;
                stop)
                    sudo kill "$(head -1 /var/run/ppp-rmg-vpn.pid)"
                ;;
            esac
        ;;
    esac
}

route-rmg() {
    # This is naive, but it should work for RMG stuff
    mapfile -t ips < <(dig +short "$1.regentmarkets.com")

    for ip in "${ips[@]}"; do
        if [[ "${ip: -1}" != "." ]]; then
            sudo ip route add "$ip"/32 via 192.168.12.229 dev ppp0 onlink
        fi
    done
}
