#!/bin/bash
shopt -s nullglob

[[ -d patches ]] || mkdir patches
rm patches/*.diff 2>/dev/null

for file in *; do
    [[ -f /etc/xdg/luakit/$file ]] || continue
    diff -u /etc/xdg/luakit/"$file" "$file" > patches/"$file".diff && rm patches/"$file".diff
done
