#!/bin/bash

key_combo="${1?}"
mapfile -t files

rotate() {
    local degrees="${1?}"
    for file in "${files[@]}"; do
        jpegtran -rotate "$degrees" -trim -copy all -outfile "$file" "$file"
    done
}

case $key_combo in
    C-d) rm -- "${files[@]}" ;;
    C-l) rotate 270 ;;
    C-r) rotate 90 ;;
    C-s)
        readlink -f "${files[@]}" | tee /tmp/sxivfiles | xclip -sel clip
    ;;
esac
