#!/bin/bash

set -e

rm -rf /tmp/github-backup
mkdir -p /tmp/github-backup/repos

cd /tmp/github-backup

git clone git://github.com/cdown/gh-mirror.git

cd repos

../gh-mirror/gh-mirror --exclude linux --exclude systemd --exclude fbkutils --exclude quickstack --exclude regex --exclude nom cdown

cd ..
