[build]
# See https://github.com/rust-lang/rust/issues/48371,
# https://github.com/rust-lang/rust/issues/47866 and others for information on
# why LTO isn't being used
rustflags = ["-C", "target-cpu=native", "-C", "opt-level=2"]

[profile.profiling]
inherits = "release"
debug = true
