#!/bin/bash

alias be='bundle exec'
alias fp='readlink -f'
alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias mutt-patch='mutt -F ~/.config/mutt/rc-patch -H'
alias proxy='ssh -C2qTnN -D 1337'
alias sc=systemctl
alias sprunge='curl -F "sprunge=<-" http://sprunge.us'
alias ssh='TERM=rxvt ssh'
alias sudo='sudo '
alias v='ls -laFh'
alias vbox-mods='modprobe -a vboxdrv vboxnetadp vboxnetflt vboxpci'
