#!/bin/bash

alias mutt-patch='mutt -F ~/.config/mutt/rc-patch -H'
alias be='bundle exec'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias v='ls -laFh'
alias sprunge='curl -F "sprunge=<-" http://sprunge.us'
alias sc=systemctl
alias ssh='TERM=rxvt ssh'
alias sudo='sudo '
alias proxy='ssh -C2qTnN -D 1337'
alias fp='readlink -f'
