#!/bin/bash

awk 'NR==FNR && !/^#/{lines[$0]=FNR;next} lines[$0]==FNR' "$HISTFILE" "$HISTFILE" > "$HISTFILE.compressed"
mv "$HISTFILE.compressed" "$HISTFILE"

HISTFILESIZE=
HISTSIZE=

HISTCONTROL=ignoredups
PROMPT_COMMAND='history -a'

shopt -s histappend
shopt -s extglob
shopt -s globstar

set +H

gitPrompt() {
    git branch --no-color 2>/dev/null | awk '/^\*/ { print ":" $2 }'
}

PS1='\u@\h:\W$(gitPrompt)\$ '
