#!/bin/bash

awk 'NR==FNR && !/^#/{lines[$0]=FNR;next} lines[$0]==FNR' "$HISTFILE" "$HISTFILE" > "$HISTFILE.compressed"
mv "$HISTFILE.compressed" "$HISTFILE"

HISTFILESIZE=
HISTSIZE=

HISTCONTROL=ignoredups
PROMPT_COMMAND='history -a'

shopt -s histappend
shopt -s extglob
shopt -s globstar

set +H

git_prompt() {
    local branch

    if branch="$(git symbolic-ref --short -q HEAD 2>/dev/null)"; then
        printf ':%s' "$branch"
    fi
}

PS1='\u@\h:\W$(git_prompt)\$ '
