#!/bin/bash

alias be='bundle exec'
alias fp='readlink -f'
alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias mutt-patch='mutt -F ~/.config/mutt/rc-patch -H'
alias proxy='ssh -C2qTnN -D 1337'
alias sc=systemctl
alias sprunge='curl -F "sprunge=<-" http://sprunge.us'
alias ssh='TERM=rxvt ssh'
alias sudo='sudo '
alias v='ls -laFh'
alias vbox-mods='modprobe -a vboxdrv vboxnetadp vboxnetflt vboxpci'
alias refresh-mirrors='sudo reflector -f 6 -c Japan -c Australia -c Korea --sort rate --save /etc/pacman.d/mirrorlist'

record-screen() {
    ffmpeg -f x11grab -r 25 -s "$1" -i :0.0+0,0 -vcodec libx264 -threads 0 "$2"
}

f() {
    find "${2-.}" -iname "*$1*"
}

chromium-proxy() {
    pkill -f chromium
    proxy guthrie &
    sleep 5
    chromium --incognito --proxy-server=socks5://localhost:1337
    kill "$!"
}
