#!/bin/bash

declare -A JUMP_DIRS

jump() {
    (( $# == 1 )) || return 1
    dir="${JUMP_DIRS[$1]}"
    if ! [[ $dir ]]; then
        printf 'No such jump name: %s\n' "$1" >&2
        return 1
    fi
    cd "$dir"
}

alias j=jump

JUMP_DIRS=(
    [bom]="$HOME/git/rmg/bom"
    [git]="$HOME/git"
    [dl]="$HOME/Downloads"
)
