#!/bin/bash

type gpg-agent >/dev/null 2>&1 || return

export GPG_TTY=$(tty)

[[ -r ~/.gpg-agent ]] && . ~/.gpg-agent >/dev/null

if (( EUID )) && ! gpg-agent >/dev/null 2>&1; then
    eval "$(gpg-agent --daemon | tee ~/.gpg-agent)" >/dev/null
fi
