#!/bin/sh

alias coa=create-or-attach-tmux-session
alias sbdl=seedbox-download
alias sbls=seedbox-ls
alias so=clean-env
alias udf=update-dotfiles
alias zhsub=fix-chinese-sub-encoding
alias v=virtualenv-auto
alias p=ipython
alias u='udf && exec zsh -l'
alias m=moshrc
alias s=sshrc
alias b='sudo intel-brightness'

# virtualenvwrapper
alias mv2='mkvirtualenv -p python2'
alias mv3='mkvirtualenv -p python3'
alias wo=workon
