#!/bin/sh

alias coa=create-or-attach-tmux-session
alias so=clean-env
alias udf=update-dotfiles
alias zhsub=fix-chinese-sub-encoding
alias p=ipython
alias u='udf && exec zsh -l'
alias s=sshrc
alias b='sudo brightness'
alias x='s -l root'
alias q='sudo '
alias lopri='nice -n 19 ionice -c2 -n7 '
alias pp='pdfpc -n right --disable-auto-grouping'
alias scan='sudo nmap -n -PN -sT -sU -p-'
alias k='q apt-get update && q apt-get dist-upgrade && q apt-get autoremove'
alias cf='clang-format -i -style=file'

alias ss='sudo systemctl start'
alias st='sudo systemctl stop'
alias sd='sudo systemctl -n 100 status'

alias us='systemctl --user start'
alias ut='systemctl --user stop'
alias ud='systemctl --user -n 100 status'

alias mtp-on='mtpfs -o allow_other /mnt/mtp'
alias mtp-off='fusermount -u /mnt/mtp'

alias pngquant='pngquant -f --ext .png'

m() {
    moshrc "$@"
}

g(){
    gdb -q /proc/"${1?}"/exe "$1"
}

d() {
    tmux new-session -s "oneoff-${1?}-$(date +%Y%m%d%H%M%S)" -- "$@"
}
alias d='d '

transfer() {
    curl --upload-file "${1?}" https://transfer.sh
}

# virtualenvwrapper
alias mv2='mkvirtualenv -p "$(command -v python2)"'
alias mv3='mkvirtualenv -p "$(command -v python3)"'
alias wo=workon

alias gt=grep-tids

alias gam='xgamma -gamma 3'

alias fix-netctl='q rm /run/network/wpa_supplicant_wlp4s0.conf'  # lol
alias wipe-disk='shred --verbose --random-source=/dev/urandom -n1'

alias chinese-only='srt lines-matching -m hanzidentifier -f hanzidentifier.has_chinese'
alias strip-html="srt process -m re -f 'lambda sub: re.sub("'"<[^<]+?>", "", sub'")'"
alias strip-format="srt process -m re -f 'lambda sub: re.sub("'"{[^{]+?}", "", sub'")'"
alias simplify='cconv -f utf-8 -t utf-8-cn'

alias rustfmt='rustfmt --config-path ~/.config/rustfmt'

alias pw='LC_ALL=C tr -dc a-zA-Z0-9 < /dev/urandom | head -c 20; echo'

alias wine32='WINEARCH=win32 WINEPREFIX="$HOME/.wine32" wine'
alias winecfg32='WINEARCH=win32 WINEPREFIX="$HOME/.wine32" winecfg'
