#!/bin/sh

alias cdg='cd "$(git rev-parse --show-toplevel)"'

# Base commands that set command defaults
alias ga='git add'
alias gb='git branch'
alias gc='git commit -v'
alias gco='git checkout'
alias gd='git diff --no-prefix'
alias gf='git fetch -p'
alias gg='git grep'
alias gl='git log'
alias gm='git merge --no-ff'
alias gp='git push'
alias gs='git show'
alias gst='git status'

# Rebasing
alias grp='git rebase -p'
alias gri='grp -i'
alias grim='gri master@{u}'
alias grpm='grp master@{u}'
alias grid='gri develop@{u}'
alias grpd='grp develop@{u}'
alias gru='grp @{u}'

# Diffing
alias gdm='gd master@{u}..'
alias gdd='gd develop@{u}..'
alias gdu='gd @{u}..'
alias gdc='gd --cached'
alias gdw='gd --color-words'

# Logs
alias glm='gl master@{u}..'
alias gld='gl develop@{u}..'
alias glu='gl @{u}..'

# Misc
alias gap='ga -p'
alias gbr='gb -r'
alias gca='gc -a'
alias gcaa='gca --amend'
alias grh='git reset --hard'
alias grhu='grh @{u}'
alias gpf='gp -f'
alias grcp='git re-cherry-pick'
alias gcm='git cleanup-merged'
