#!/bin/sh

for env in pyenv rbenv nodenv plenv; do
    if command -v "$env" >/dev/null 2>&1; then
        eval "$("$env" init - --no-rehash "${0#-}")"
    fi
done

export PATH="$config_home/.local/bin:$HOME/.local/bin:$PATH"
