#!/bin/sh

colour_part() {
    local colour="$1"
    local msg="$2"
    local delim="${3- }"

    [ "$msg" ] || return 1

    if [ "$BASH" ]; then
        printf '%s ' "$msg"
    elif [ "$ZSH_VERSION" ]; then
        printf '%%{%s%%}%s%%{%s%%}'"${delim}" "$(tput setaf "$colour")" "$msg" "$(tput sgr0)"
    fi

}

_hg_prompt() {
    local hg_bookmark
    hg_bookmark=$(hg bookmarks 2>/dev/null | awk '/\*/ { print $2 }')
    colour_part 2 "$hg_bookmark"
}

_git_prompt() {
    local branch
    local git_state
    local git_head
    local git_dir
    local tag

    if branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"; then
        if [ "$branch" != HEAD ]; then
            git_head=$branch
        elif tag="$(git describe --tags --exact-match HEAD 2>/dev/null)"; then
            git_head=$tag
        else
            git_head=$(git rev-parse --short HEAD)
        fi

        git_dir=$(git rev-parse --git-dir)

        if [ -d "$git_dir/rebase-apply" ]; then
            git_state=rebase
        elif [ -d "$git_dir/rebase-merge" ]; then
            git_state=rebase
        elif [ -f "$git_dir/MERGE_HEAD" ]; then
            git_state=merge
        elif [ -f "$git_dir/CHERRY_PICK_HEAD" ] || [ -f .git/sequencer/todo ]; then
            git_state=cherry-pick
        elif [ -f "$git_dir/REVERT_HEAD" ]; then
            git_state=revert
        elif [ -f "$git_dir/BISECT_LOG" ]; then
            git_state=bisect
        fi
    fi

    [ "$git_head" = master ] && unset git_head

    colour_part 2 "$git_head"
    colour_part 1 "$git_state"
}

_virt_prompt() {
    # We assume virtualisation won't change for one shell session
    if [ "$_VIRT" ]; then
        # Skip other branches
        :
    elif [ "${JUNEST_ENV:-0}" -eq 1 ]; then
        _VIRT=junest
    else
        _VIRT=$(systemd-detect-virt 2>/dev/null)
        if [ "$_VIRT" = none ]; then
            unset _VIRT
        fi
    fi

    colour_part 6 "$_VIRT"
}

_hostname_prompt() {
    local hostname

    if ! [ "$SSH_CLIENT" ]; then
        return
    fi

    if ! [ "$_HOSTNAME" ]; then
        hostname=$(cat /etc/hostname 2>/dev/null || hostname)
        _HOSTNAME="${hostname%%.*}"
    fi

    colour_part 3 "$_HOSTNAME"
}

_user_prompt() {
    local user

    # Still skip if it's empty, only go in if unset
    if ! [ "${_USER+x}" ]; then
        user=$(id -un)
        case $user in
            cdown|chris|lin|neuro) _USER='' ;;
            *) _USER=$user ;;
        esac
    fi

    colour_part 3 "${_USER:+"$_USER@"}" ''
}

_pwd_prompt() {
    local current_dir
    local stripped_pwd

    if [ "$PWD" = "$HOME" ]; then
        return
    else
        stripped_pwd=${PWD##*/}
        if [ "$stripped_pwd" ]; then
            current_dir=$stripped_pwd
        else
            current_dir=/
        fi
    fi

    colour_part 4 "$current_dir"
}

_get_ps1() {
    local prompt
    local prompt_ender

    if [ "$ZSH_VERSION" ]; then
        prompt_ender="%(?:%%:%{$(tput setaf 1)%}%%%{%{$(tput sgr0)%}%})"
    else
        prompt_ender=%
    fi

    prompt="$(_user_prompt)$(_hostname_prompt)$(_pwd_prompt)$(_git_prompt)$(_hg_prompt)"
    printf '%s%s ' "$prompt" "$prompt_ender"
}

# Mostly for WSL, since on Linux I don't have window titles.
_term_title() {
    printf '\e]0;%s\a' "${1?}"
}
