#!/bin/sh

alias cdg='cd "$(git rev-parse --show-toplevel)"'

# Base commands that set command defaults
alias ga='git add'
alias gb='git branch'
alias gc='git commit -v'
alias gco='git checkout'
alias gcp='git cherry-pick --strategy=recursive --strategy-option=diff-algorithm=histogram'
alias gd='git diff --no-prefix'
alias gg='git grep'
alias gl='git log'
alias gm='git merge'
alias gmc='gm --no-ff'
alias gp='git push'
alias gs='git show --no-prefix'
alias gst='git status'
alias gref='git reflog --date=iso'

gf() {
    if [ "$1" ]; then
        git fetch -p "$1"
    else
        git fetch -p -j99 --all
    fi
}

gfic() {
    git diff-tree --no-commit-id --name-only -r "${1-HEAD}"
}

gcopr() {
    git fetch origin pull/"${1?need pr num}"/head:pr"$1" && gco pr"$1"
}

gnb() {
    git checkout -b "$USER"/"$(date +%F)"/"${1?name missing}" "${2:-HEAD}"
}

ggbl() {
    git grep -n "${1?}" | perl -F: -anpe '$_=`git blame -fL$F[1],+1 $F[0]`'
}

hnb() {
    local name
    name="$USER"/"$(date +%F)"/"${1?name missing}"

    hg bookmark -r "${2:-.}" "$name"
    hg update "$name"
}

# git-send-patch style
alias gsp='mutt-patch'

# Rebasing
alias grr='git rebase -r'
alias gri='grr -i'
alias grim='gri master@{u}'
alias grrm='grr master@{u}'
alias grid='gri develop@{u}'
alias grrd='grr develop@{u}'
alias gru='grr @{u}'

# Diffing
git-diff-merge-base() {
    local feature="${2-HEAD}"
    gd "$(git merge-base "$1" "$feature")..$feature"
}

alias gdm='git-diff-merge-base master@{u}'
alias gdd='git-diff-merge-base develop@{u}'
alias gdu='gd @{u}..'
alias gdc='gd --cached'
alias gdw='gd --color-words'

# Logs
alias glm='gl master@{u}..'
alias gld='gl develop@{u}..'
alias glu='gl @{u}..'

# Misc
alias gap='ga -p'
alias gbr='gb -r'
alias gca='gc -a'
alias gcaa='gca --amend'
alias grh='git reset --hard'
alias grhu='grh @{u}'
alias gpf='gp -f'
alias gu='gf && grrm'
alias gcl='git clean -dffx'

# Mercurial
alias ha='hg add'
alias hb='hg bookmark'
alias hc='hg commit'
alias hd='hg diff'
alias hdm='hdr "ancestor(master, .)"'
alias hdr='hd -r'
alias hhem='hdm > /tmp/q && hg --debug --traceback histedit "::. and not ::master"'
alias hl='hg log'
alias hlm='hl -r "::. and not ::master"'
alias hp='hg pull'
alias hr='hg rebase'
alias hrm='hr -d master'
alias hs='hg show'
alias hst='hg status'
alias hu='hg update'
alias huc='hu --clean'
alias hbs=hg-bookmark-strip

hg-bookmark-strip() {
    local bookmark="${1?bookmark required}"
    hg strip -r "$bookmark"
    hg bookmark --delete "$bookmark"
}

# Arcanist
alias ab='arc build'
alias ad='arc diff'
alias adp='ad --preview'
alias af='arc feature'
alias afc='arc feature --cleanup'
alias al='arc land'
alias all='al --local'
alias ap='arc pull'
