#!/bin/sh

alias cdg='cd "$(git rev-parse --show-toplevel)"'

# Base commands that set command defaults
alias ga='git add'
alias gb='git branch'
alias gc='git commit -v'
alias gco='git checkout'
alias gd='git diff --no-prefix'
alias gf='git fetch -p'
alias gg='git grep'
alias gl='git log'
alias gm='git merge --no-ff'
alias gp='git push'
alias gs='git show --no-prefix'
alias gst='git status'

# Rebasing
alias grp='git rebase -p'
alias gri='grp -i'
alias grim='gri master@{u}'
alias grpm='grp master@{u}'
alias grid='gri develop@{u}'
alias grpd='grp develop@{u}'
alias gru='grp @{u}'

# Diffing
git-diff-merge-base() {
    local feature="${2-HEAD}"
    gd "$(git merge-base "$1" "$feature")..$feature"
}

alias gdm='git-diff-merge-base master@{u}'
alias gdd='git-diff-merge-base develop@{u}'
alias gdu='gd @{u}..'
alias gdc='gd --cached'
alias gdw='gd --color-words'

# Logs
alias glm='gl master@{u}..'
alias gld='gl develop@{u}..'
alias glu='gl @{u}..'

# Misc
alias gap='ga -p'
alias gbr='gb -r'
alias gca='gc -a'
alias gcaa='gca --amend'
alias grh='git reset --hard'
alias grhu='grh @{u}'
alias gpf='gp -f'
alias gu='gf && grpm'
alias gcl='git clean -dffx'

# Mercurial
alias ha='hg add'
alias hb='hg bookmark'
alias hc='hg commit'
alias hd='hg diff'
alias hdm='hdr "ancestor(master, .)"'
alias hdr='hd -r'
alias hhem='hg histedit "::. and not ::master"'
alias hl='hg log'
alias hlm='hl -r "::. and not ::master"'
alias hp='hg pull'
alias hr='hg rebase'
alias hrm='hr -d master'
alias hs='hg show'
alias hst='hg status'
alias hu='hg update'
alias huc='hu --clean'

# Arcanist
alias ab='arc build'
alias ad='arc diff'
alias adp='ad --preview'
alias af='arc feature'
alias afc='arc feature --cleanup'
alias al='arc land'
alias all='al --local'
alias ap='arc pull'
