#!/bin/zsh

zstyle ':completion:*:default' list-colors "${(s.:.)LS_COLORS}"

if [[ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
    . /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi
