#!/bin/zsh

set -o always_to_end
set -o append_history
set -o complete_in_word
set -o extendedglob
set -o histappend
set -o histignorealldups
set -o histignorespace
set -o interactivecomments
set -o ksh_glob
set -o no_bang_hist
set -o no_bare_glob_qual
set -o no_extended_glob
set -o noclobber
set -o nullglob
set -o prompt_subst
set -o rmstarsilent
set -o shwordsplit
