#!/bin/sh

mktemp_cmd=mktemp
command -v gmktemp >/dev/null 2>&1 && mktemp_cmd=gmktemp # Mac

in_temp=$("$mktemp_cmd")
out_temp=$("$mktemp_cmd")

cat > "$in_temp"

for filter in ~/.config/mutt/filters/*; do
    "$filter" < "$in_temp" > "$out_temp"
    cp "$out_temp" "$in_temp"
done

cat "$in_temp"

rm -f "$in_temp" "$out_temp"
