#!/bin/bash

LS_COLORS='rs=0:di=01;34:ln=01;36:mh=38;5;220;1:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:'

hide=(
    .viminfo
    .Xauthority
    .ssh-agent
    .rediscli_history
    .lesshst
    .bash_history
    .gitignore
    .pyc
    .pyo
)

for hidden in "${hide[@]}"; do
    LS_COLORS+="*$hidden=1;30:"
done

export LS_COLORS
